site_name: SITES Spectral Thematic Center (SSTC) - Schemas

theme:
  name: 'rtd-dropdown'

plugins:
  - search
  - mkdocstrings
  - include-markdown

markdown_extensions:
  - toc:
      permalink: true